### ISSUE TITLE
Feature: Fazer a feature que define o sintoma em alta

### ISSUE THREAD

**Issue by ocai0** [vhdtv/Projeto-Pratico#10]
**Dificuldade**: baixa (tem exemplos parecidos)
**Task**: Fazer um código que retorna o sintoma mais reportado pelo paciente (dá pra procurar com a tabela 'tb_report_xref_symptom')
**URL para acessar**: http://localhost:8090/dashboard

**Comment by LucasAndradeF** [comment]
Resolvido

**Comment by LucasAndradeF** [comment]
Resolvido
